import { ExternalSchool, IntercollegiateEventKey } from '../types';

export const EVENT_DEFINITIONS: {
  key: IntercollegiateEventKey;
  label: string;
  shortLabel: string;
  type: 'deporte' | 'academico';
  badgeBg: string;
  badgeText: string;
  badgeBorder: string;
}[] = [
  {
    key: 'futbol',
    label: 'Interescolar Fútbol',
    shortLabel: 'Fútbol',
    type: 'deporte',
    badgeBg: 'bg-emerald-50',
    badgeText: 'text-emerald-800',
    badgeBorder: 'border-emerald-200',
  },
  {
    key: 'beachtennis',
    label: 'Beach Tennis Intercolegial',
    shortLabel: 'Beach Tennis',
    type: 'deporte',
    badgeBg: 'bg-amber-50',
    badgeText: 'text-amber-800',
    badgeBorder: 'border-amber-200',
  },
  {
    key: 'spelling_bee',
    label: 'Spelling Bee (Inglés)',
    shortLabel: 'Spelling Bee',
    type: 'academico',
    badgeBg: 'bg-purple-50',
    badgeText: 'text-purple-800',
    badgeBorder: 'border-purple-200',
  },
  {
    key: 'deletreo_espanol',
    label: 'Deletreo en Español',
    shortLabel: 'Deletreo',
    type: 'academico',
    badgeBg: 'bg-blue-50',
    badgeText: 'text-blue-800',
    badgeBorder: 'border-blue-200',
  },
  {
    key: 'ajedrez',
    label: 'Torneo de Ajedrez',
    shortLabel: 'Ajedrez',
    type: 'academico',
    badgeBg: 'bg-slate-100',
    badgeText: 'text-slate-800',
    badgeBorder: 'border-slate-300',
  },
];

export const INITIAL_SCHOOLS_DATA: ExternalSchool[] = [
  {
    id: 'sch-01',
    name: 'Colegio La Paz',
    emails: ['colegio.nstra.sra.de.la.paz@gmail.com'],
    contactPhone: '0281-2762310',
    events: {
      futbol: false,
      beachtennis: false,
      spelling_bee: false,
      deletreo_espanol: true,
      ajedrez: false,
    },
    notes: 'Sede Puerto La Cruz',
  },
  {
    id: 'sch-02',
    name: 'Colegio Andrés Eloy Blanco',
    emails: ['igualdadyjusticia@hotmail.com'],
    contactName: 'Lérida Velásquez',
    contactPhone: '0424-8040990',
    events: {
      futbol: false,
      beachtennis: false,
      spelling_bee: false,
      deletreo_espanol: false,
      ajedrez: false,
    },
  },
  {
    id: 'sch-03',
    name: 'Colegio Ángel Mottola',
    emails: ['ueiangelmottola1994@gmail.com', 'luzmilapyme@gmail.com'],
    contactName: 'Luzmila Godoy',
    contactPhone: '0414-8251494',
    events: {
      futbol: false,
      beachtennis: false,
      spelling_bee: false,
      deletreo_espanol: false,
      ajedrez: true,
    },
  },
  {
    id: 'sch-04',
    name: 'Colegio Don Bosco',
    emails: ['colegiodb.bna.pe1@gmail.com'],
    contactName: 'Coordinación Don Bosco',
    events: {
      futbol: false,
      beachtennis: false,
      spelling_bee: false,
      deletreo_espanol: true,
      ajedrez: true,
    },
    notes: 'Sede Barcelona',
  },
  {
    id: 'sch-05',
    name: 'Colegio Italo Venezolano',
    emails: ['soporte@colegioitalopic.edu.ve'],
    contactName: 'Evelin Palou',
    contactPhone: '0414-8100096',
    events: {
      futbol: true,
      beachtennis: true,
      spelling_bee: false,
      deletreo_espanol: false,
      ajedrez: false,
    },
  },
  {
    id: 'sch-06',
    name: 'Colegio Julio Garmendia',
    emails: ['uejuliogarmendiamurrieta@gmail.com', 'guillenlanguageacademy@gmail.com'],
    contactName: 'Jaqueline Olivares',
    contactPhone: '0414-8215666',
    secondaryContact: 'Sede Colegio: 0281-2810306',
    events: {
      futbol: false,
      beachtennis: false,
      spelling_bee: true,
      deletreo_espanol: false,
      ajedrez: true,
    },
  },
  {
    id: 'sch-07',
    name: 'Colegio Laura Vicuña',
    emails: ['uecolegiolv@gmail.com'],
    contactName: 'Vivian Brasa',
    contactPhone: '0414-8206852',
    events: {
      futbol: false,
      beachtennis: false,
      spelling_bee: false,
      deletreo_espanol: false,
      ajedrez: false,
    },
  },
  {
    id: 'sch-08',
    name: 'Colegio Libertador',
    emails: [],
    contactName: 'Carmen',
    events: {
      futbol: false,
      beachtennis: false,
      spelling_bee: false,
      deletreo_espanol: false,
      ajedrez: false,
    },
  },
  {
    id: 'sch-09',
    name: 'Colegio MAPIS',
    emails: ['english@uempis.org'],
    contactName: 'Gletxis Guacaran',
    contactPhone: '0414-7774006',
    secondaryContact: 'Delania Alcalá: 0416-6800233',
    events: {
      futbol: false,
      beachtennis: false,
      spelling_bee: true,
      deletreo_espanol: false,
      ajedrez: true,
    },
  },
  {
    id: 'sch-10',
    name: 'Colegio María Auxiliadora',
    emails: [],
    contactName: 'Coordinación María Auxiliadora',
    events: {
      futbol: false,
      beachtennis: true,
      spelling_bee: true,
      deletreo_espanol: false,
      ajedrez: true,
    },
  },
  {
    id: 'sch-11',
    name: 'Colegio Nuestra Señora del Valle',
    emails: ['ntrasdelvalle@gmail.com'],
    contactName: 'Hermana Nancy Meléndez',
    contactPhone: '0424-9225719',
    events: {
      futbol: false,
      beachtennis: false,
      spelling_bee: false,
      deletreo_espanol: false,
      ajedrez: false,
    },
  },
  {
    id: 'sch-12',
    name: 'Colegio Río Orinoco',
    emails: ['colegiorioorinoco@gmail.com'],
    events: {
      futbol: false,
      beachtennis: false,
      spelling_bee: true,
      deletreo_espanol: true,
      ajedrez: true,
    },
  },
  {
    id: 'sch-13',
    name: 'E.B. Inés María de Potentini',
    emails: ['impotentini@yahoo.es'],
    contactName: 'Yangelina Peaspan',
    contactPhone: '0424-8239737',
    events: {
      futbol: false,
      beachtennis: false,
      spelling_bee: false,
      deletreo_espanol: true,
      ajedrez: false,
    },
  },
  {
    id: 'sch-14',
    name: 'E.P.B. Campo Alegre',
    emails: ['eb.campoalegre@hotmail.com'],
    contactName: 'Martha Rodríguez',
    contactPhone: '0424-8448886',
    events: {
      futbol: false,
      beachtennis: false,
      spelling_bee: false,
      deletreo_espanol: false,
      ajedrez: false,
    },
  },
  {
    id: 'sch-15',
    name: 'Instituto de Enseñanza América Latina',
    emails: ['infoueideal@gmail.com'],
    contactPhone: '0282-2861080',
    events: {
      futbol: false,
      beachtennis: true,
      spelling_bee: false,
      deletreo_espanol: false,
      ajedrez: true,
    },
  },
  {
    id: 'sch-16',
    name: 'La Consolación',
    emails: [],
    contactName: 'Coordinación La Consolación',
    events: {
      futbol: true,
      beachtennis: true,
      spelling_bee: false,
      deletreo_espanol: false,
      ajedrez: true,
    },
  },
  {
    id: 'sch-17',
    name: 'Licdo. Diego B. Urbaneja',
    emails: [],
    contactName: 'Lideth',
    contactPhone: '0416-4808333',
    events: {
      futbol: false,
      beachtennis: true,
      spelling_bee: false,
      deletreo_espanol: false,
      ajedrez: false,
    },
  },
  {
    id: 'sch-18',
    name: 'Los Próceres',
    emails: ['ueclosproceresprimaria@gmail.com'],
    contactName: 'Rafael Cardozo',
    contactPhone: '0424-8056658',
    secondaryContact: 'MARIA RIVAS: 0414-7968583',
    events: {
      futbol: false,
      beachtennis: false,
      spelling_bee: false,
      deletreo_espanol: false,
      ajedrez: true,
    },
  },
  {
    id: 'sch-19',
    name: 'San Onofre',
    emails: [
      'controldeestudios.sanonofre@gmail.com',
      'subdireccionsanonofre@gmail.com',
      'ariasleonjavier@gmail.com',
    ],
    contactName: 'Javier',
    contactPhone: '0424-8983726',
    secondaryContact: 'Gladis Leon: 0414-8299424 / Jennifer Rivero: 0412-0850378',
    events: {
      futbol: false,
      beachtennis: false,
      spelling_bee: false,
      deletreo_espanol: false,
      ajedrez: true,
    },
  },
  {
    id: 'sch-20',
    name: 'U. E. Juan Jacobo Rousseau (nuevo)',
    emails: [
      'ue.caciqaurimare.plc@gmail.com',
      'director.urimare2024@gmail.com',
      'directorgeneral.urimare@gmail.com',
    ],
    contactName: 'Jeydis Friman',
    contactPhone: '0412-6962818',
    secondaryContact: 'informacion.curimare',
    events: {
      futbol: false,
      beachtennis: false,
      spelling_bee: false,
      deletreo_espanol: true,
      ajedrez: false,
    },
  },
  {
    id: 'sch-21',
    name: 'U. E. Cristóbal Rojas',
    emails: ['uecristobalrojas1999@gmail.com', 'u.e.a.i.juan.jacobo.rousseau@gmail.com'],
    events: {
      futbol: false,
      beachtennis: false,
      spelling_bee: false,
      deletreo_espanol: true,
      ajedrez: false,
    },
  },
  {
    id: 'sch-22',
    name: 'U. E. Nuestra Señora de Lourdes I',
    emails: ['colegiolourdes1@gmail.com'],
    contactName: 'Prof. Rosa León',
    contactPhone: '0414-3816247',
    events: {
      futbol: false,
      beachtennis: false,
      spelling_bee: false,
      deletreo_espanol: false,
      ajedrez: true,
    },
  },
  {
    id: 'sch-23',
    name: 'U. E. Nuestra Señora de Lourdes II',
    emails: ['LAREVALO@COLEGIODELOUDES.COM'],
    contactName: 'Willian Palacios',
    contactPhone: '0412-4981164',
    events: {
      futbol: true,
      beachtennis: true,
      spelling_bee: true,
      deletreo_espanol: false,
      ajedrez: false,
    },
  },
  {
    id: 'sch-24',
    name: 'U. E. República de Venezuela',
    emails: ['republicadevenezuela2@gmail.com'],
    contactPhone: '0281-2818665 / 0281-2813345',
    events: {
      futbol: false,
      beachtennis: false,
      spelling_bee: false,
      deletreo_espanol: true,
      ajedrez: false,
    },
  },
  {
    id: 'sch-25',
    name: 'U. E. Río Orinoco',
    emails: ['colegiorioorinoco@gmail.com'],
    events: {
      futbol: false,
      beachtennis: false,
      spelling_bee: false,
      deletreo_espanol: true,
      ajedrez: false,
    },
  },
  {
    id: 'sch-26',
    name: 'U. E. Rodolfo Romero',
    emails: ['uerodolforomero@gmail.com'],
    events: {
      futbol: true,
      beachtennis: true,
      spelling_bee: false,
      deletreo_espanol: true,
      ajedrez: false,
    },
  },
  {
    id: 'sch-27',
    name: 'U. E. San Lázaro',
    emails: [],
    contactName: 'Coordinación San Lázaro',
    events: {
      futbol: false,
      beachtennis: true,
      spelling_bee: false,
      deletreo_espanol: true,
      ajedrez: false,
    },
  },
  {
    id: 'sch-28',
    name: 'U.E Colegio Guayamurí',
    emails: ['coordinaciondeingles@guayamuri.org'],
    contactName: 'Michelle Santiago',
    contactPhone: '0414-7960333',
    events: {
      futbol: false,
      beachtennis: false,
      spelling_bee: true,
      deletreo_espanol: true,
      ajedrez: false,
    },
  },
  {
    id: 'sch-29',
    name: 'U.E Juan Crisóstomo Falcón',
    emails: ['coordinacionjcf22@gmail.com', 'menmarianella@gmail.com'],
    contactName: 'Subdirectora Anaida Guedez',
    contactPhone: '0424-6200917',
    events: {
      futbol: false,
      beachtennis: true,
      spelling_bee: false,
      deletreo_espanol: false,
      ajedrez: false,
    },
  },
  {
    id: 'sch-30',
    name: 'U.E. Colegio Santa María',
    emails: ['carmenjoachiques04@gmail.com'],
    contactName: 'Carmen Achiques',
    contactPhone: '0426-3837905',
    events: {
      futbol: false,
      beachtennis: false,
      spelling_bee: false,
      deletreo_espanol: true,
      ajedrez: false,
    },
  },
  {
    id: 'sch-31',
    name: 'U.E. Dr. Raúl Leoni',
    emails: ['emiliedearcia@hotmail.com', 'caracolitomagico2@gmail.com'],
    contactName: 'Emilia de Arcia',
    events: {
      futbol: false,
      beachtennis: false,
      spelling_bee: false,
      deletreo_espanol: false,
      ajedrez: true,
    },
  },
  {
    id: 'sch-32',
    name: 'U.E. Francisco Lazo Martí',
    emails: ['didaskalia.a@gmail.com', 'mb.beyourself@gmail.com'],
    contactName: 'José R. Álvarez',
    contactPhone: '0424-2596849',
    events: {
      futbol: false,
      beachtennis: true,
      spelling_bee: true,
      deletreo_espanol: false,
      ajedrez: false,
    },
  },
  {
    id: 'sch-33',
    name: 'U.E. Juan Vicente González',
    emails: ['uecjuanvicentegonzalez@gmail.com'],
    contactName: 'Lisbelia Márquez',
    contactPhone: '0281-2762831',
    events: {
      futbol: false,
      beachtennis: false,
      spelling_bee: false,
      deletreo_espanol: false,
      ajedrez: false,
    },
  },
  {
    id: 'sch-34',
    name: 'U.E. Nuestra Sra. de las Nieves',
    emails: [],
    contactName: 'Milagros González',
    events: {
      futbol: false,
      beachtennis: false,
      spelling_bee: false,
      deletreo_espanol: true,
      ajedrez: false,
    },
  },
];
